---
# - ros_topic_name: "/diff_drive/cmd_vel"
#   gz_topic_name: "/model/diff_drive/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "ignition.msgs.Twist"
#   direction: ROS_TO_GZ

# - ros_topic_name: "/diff_drive/odometry"
#   gz_topic_name: "/model/diff_drive/odometry"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "ignition.msgs.Odometry"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/diff_drive/scan"
#   gz_topic_name: "/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "ignition.msgs.LaserScan"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/clock"
#   gz_topic_name: "/clock"
#   ros_type_name: "rosgraph_msgs/msg/clock"
#   gz_type_name: "ignition.msgs.Clock"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/joint_states"
#   gz_topic_name: "/world/demo/model/diff_drive/joint_state"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "ignition.msgs.Model"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/tf"
#   gz_topic_name: "/model/diff_drive/pose"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "ignition.msgs.Pose_V"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/tf_static"
#   gz_topic_name: "/model/diff_drive/pose_static"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "ignition.msgs.Pose_V"
#   direction: GZ_TO_ROS

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera"
  gz_topic_name: "/camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

# - ros_topic_name: "/camera/info"
#   gz_topic_name: "/camera/info"
#   ros_type_name: ""
#   gz_type_name: ""
#   direction: GZ_TO_ROS
  
- ros_topic_name: "/depth_camera"
  gz_topic_name: "/depth_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/depth_camera/points"
  gz_topic_name: "/depth_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/model/x500_depth/odometry"
  gz_topic_name: "/model/x500_depth/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/model/x500_depth/odometry_with_covariance"
  gz_topic_name: "/model/x500_depth/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.OdometryWithCovariance"
  direction: GZ_TO_ROS

- ros_topic_name: "/model/x500_depth/pose"
  gz_topic_name: "/model/x500_depth/pose"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/model/x500_depth/pose_static"
  gz_topic_name: "/model/x500_depth/pose_static"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/world/demo/model/x500_depth/joint_state"
  gz_topic_name: "/world/demo/model/x500_depth/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS